src/routes/web.php
<?php 
use Illuminate\Support\Facades\Route;
use Genie\Schematojson\Schema\Http\Controllers\SchemaSheetController;
use Genie\Schematojson\Schema\Http\Controllers\StoragetypeController;
use Genie\Schematojson\Schema\Http\Controllers\TableController;
use Genie\Schematojson\Schema\Http\Controllers\StructureController;


use Genie\Schematojson\Schema\Http\Controllers\StorageconnectionController;
//use namespace

Route::group(['middleware' => 'web'], function () {
	Route::resource('storagetypes', StoragetypeController::class);
	Route::resource('storageconnections', StorageconnectionController::class);
	Route::resource('tables', TableController::class);
	Route::resource('json_structures', StructureController::class);

//Place your route here
Route::post('createJson', [SchemaSheetController::class, 'create'])->name('create_json');
Route::post('store', [SchemaSheetController::class, 'store'])->name('json_store');
Route::post('select', [SchemaSheetController::class, 'selectTable'])->name('json_select');
// Route::get('connect/{datasource}', [StorageconnectionController::class, 'connect'])->name('inputSpreadSheet');
Route::get('connect/{uuid}', [StorageconnectionController::class, 'connect'])->name('storageconnection');

Route::get('/columns/{key}/{uuid}',[StructureController::class, 'structure'])->name('structure');
Route::get('/editablestructure/{key}/{uuid}',[StructureController::class, 'editablestructure'])->name('editablestructure');
Route::post('/editablestructure',[StructureController::class, 'editablestructurestore'])->name('editablestructure.store');
Route::get('/json-structure/{key}/{uuid}',[StructureController::class, 'jsonStructure'])->name('structures.json');
Route::get('/table/{key}',[TableController::class, 'tables'])->name('table');
Route::get('/selectedstructure/{key}/{uuid}',[StructureController::class, 'selectedStructure'])->name('selectedstructure');
Route::post('/selectedStructureJson',[StructureController::class, 'selectedStructureJson'])->name('selectedStructure.json');
Route::get('/pdf-structure/{key}/{uuid}',[StructureController::class, 'pdfStructure'])->name('structure.pdf');
Route::post('oracle/input-spreadsheet',[SchemaSheetController::class, 'inputSpreadsheetForStore'])->name('input_json_to_excel');
Route::post('oracle/select-table',[SchemaSheetController::class, 'selectSheetForStore'])->name('selectSheet_json_to_excel');
Route::post('oracle/store-excel',[SchemaSheetController::class, 'storeExcel'])->name('store_json_to_excel');
Route::post('oracle/include-columns',[StructureController::class, 'includeColumn'])->name('include_column_json');




});

src/Models/Structure.php
<?php

namespace Genie\Schematojson\Schema\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Traits\UserTrackable;


use App\Traits\Historiable;

class Structure extends Model
{
    use UserTrackable;
    use SoftDeletes;
    
    
    use Historiable;
    protected $connection = 'keepmealone';
    protected $table = 'json_structures';
    protected $guarded = ['id'];
    

    /**
    * Get the route key for the model.
    *
    * @return string
    */
    public function getRouteKeyName()
    {
        return 'uuid';
    }

    ##ELOQUENTRELATIONSHIPMODEL##
}

src/Http/Controllers/StructureController.php
<?php

namespace Genie\Schematojson\Schema\Http\Controllers;

use Illuminate\Support\Facades\DB;
use Genie\Schematojson\Schema\Http\Requests\StructureRequest;
use Genie\Schematojson\Schema\Models\Structure;
use Illuminate\Support\Facades\Validator;
use Genie\Schematojson\Schema\Models\Storageconnection;

use Mpdf\Mpdf;

class StructureController extends StructureBaseController
{
    public function variableTypes()
    {
        $dbalDataType = ['Doctrine\DBAL\Types\IntegerType' => 'int',
        'Doctrine\DBAL\Types\StringType' => 'varchar',
        'Doctrine\DBAL\Types\DecimalType'=> 'decimal',
        "Doctrine\DBAL\Types\DateTimeType"=>'datetime',
        "Doctrine\DBAL\Types\TextType"=>'text',
        "Doctrine\DBAL\Types\DateType"=>'date',
        "Doctrine\DBAL\Types\JsonType"=>'json',
        "Doctrine\DBAL\Types\BigIntType"=>'bigint',
        "Doctrine\DBAL\Types\BooleanType"=>'boolean',
        "Doctrine\DBAL\Types\TimeType"=>'time',
        "Doctrine\DBAL\Types\SmallIntType"=>'smallint',
        "Doctrine\DBAL\Types\FloatType"=>'float',
        "Doctrine\DBAL\Types\DecimalType"=>'decimal',
        "Doctrine\DBAL\Types\BlobType"=>'varchar' //noted
        // "Doctrine\DBAL\Types\DateType"=>'date',
       ];      
       return $dbalDataType;
    }

    private function prepareConnection($storageconnection)
    {

        if(strtolower($storageconnection->storagetype_title)==='mysql'){
            $connection = [
                'driver' => strtolower($storageconnection->storagetype_title),
                'host' => $storageconnection->target,
                'port' => '3306',
                'database' => $storageconnection->storage,
                'username' => $storageconnection->client,
                'password' => $storageconnection->secret===null ? '':$storageconnection->secret,
            ];

        }
        if(strtolower($storageconnection->storagetype_title)==='oracle'){
            $connection = [
                'driver' => strtolower($storageconnection->storagetype_title),
                'host' => $storageconnection->target,
                'port' => '1521',
                'database' => $storageconnection->storage,
                'username' => $storageconnection->client,
                'password' => $storageconnection->secret===null ? '':$storageconnection->secret,
            ];
        }

        // $connection = [
        //     'driver' => strtolower($storageconnection->storagetype_title),
        //     'host' => $storageconnection->target,
        //     'port' => '1521',
        //     'database' => $storageconnection->storage,
        //     'username' => $storageconnection->client,
        //     'password' => $storageconnection->secret,
        // ];
        \Config::set('database.connections.'. $storageconnection->title, $connection);
        // dd(\Config::get('database.connections'));
            
        
    }


    public function structure($key, $uuid)
    {

        $storageconnection = Storageconnection::where('uuid', '=', $uuid)->first();
        // dd($storageconnection);
        $this->prepareConnection($storageconnection);
        
        $value = $key;
        $dbalDataType = $this->variableTypes();        
    
        $schema = DB::connection($storageconnection->title)->getDoctrineSchemaManager();
        // dd($storageconnection->title);
        $tables = $schema->listTableNames();
        
        $table = $tables[$key];
        $columns = $schema->listTableColumns($tables[$key]);
        // dd($columns);
        $types = [];
         foreach($columns as $key=>$column){
            // dd($column->toArray());
            $columnNames[$key] = $column->getType();
            $types[] = $dbalDataType[get_class($columnNames[$key])];
        }

        // dd($value);


    //   dd($dbalDataType[get_class($columnNames[4])]);
        return view('schema::structures.index',compact('columns','types','value','table'));
    }

    public function pdfStructure($key, $uuid)
    {
        $storageconnection = Storageconnection::where('uuid', '=', $uuid)->first();
        $this->prepareConnection($storageconnection);
        $value = $key;
        $dbalDataType = $this->variableTypes();        
    
        $schema = DB::connection($storageconnection->title)->getDoctrineSchemaManager();
        $tables = $schema->listTableNames();
        $table = $tables[$key];
        $columns = $schema->listTableColumns($tables[$key]);
        // dd($columns);
        $types = [];
         foreach($columns as $key=>$column){
            // dd($column->toArray());
            $columnNames[$key] = $column->getType();
            $types[] = $dbalDataType[get_class($columnNames[$key])];
        }

        $html = view('schema::structures.pdf',compact('columns','types','value','table'))->render();
        $mpdf = new Mpdf([
            'default_font_size' => 10,
        ]);
        
        
        $mpdf->WriteHTML($html);
        $mpdf->Output("{$table}.pdf", 'I');
    }

    public function editableStructure($key, $uuid)
    {
        $storageconnection = Storageconnection::where('uuid', '=', $uuid)->first();
        $this->prepareConnection($storageconnection);
        $dbalDataType = $this->variableTypes();   
    
        $schema = DB::connection($storageconnection->title)->getDoctrineSchemaManager();
        
        $tables = $schema->listTableNames();

        $table = $tables[$key];
        
        $columns = $schema->listTableColumns($tables[$key]);
        
        $types = [];
    
         foreach($columns as $key=>$column){
                $columnNames[$key] = $column->getType();
                $types[] = $dbalDataType[get_class($columnNames[$key])];
        }
        
        return view('schema::structures.editablestructure',compact('columns','types', 'table'));
    }

    public function selectedStructure($key, $uuid)
    {
        $storageconnection = Storageconnection::where('uuid', '=', $uuid)->first();
        $this->prepareConnection($storageconnection);
        $value = $key;
        $dbalDataType = $this->variableTypes();   
    
        $schema = DB::connection($storageconnection->title)->getDoctrineSchemaManager();
        
        $tables = $schema->listTableNames();

        $table = $tables[$key];
        
        $columns = $schema->listTableColumns($tables[$key]);
        
        $types = [];
    
         foreach($columns as $key=>$column){
                $columnNames[$key] = $column->getType();
                $types[] = $dbalDataType[get_class($columnNames[$key])];
        }
        
        return view('schema::structures.selectedstructure',compact('columns','types', 'table', 'value', 'uuid'));
    }

    public function selectedStructureJson(StructureRequest $request)
    {

        $key = $request->input('key');
        $uuid = $request->input('uuid');
        $columns = $request->input('column', []);
        $aleas = $request->input('aleas', []); 
        // $selected = $request->input('selected', []);
        $selected = $request->input('selected_items', '');
        $selectedArray = explode(',', $selected);

        $selectedArray = array_filter($selectedArray);
        
        // dd($selectedArray);

        $storageconnection = Storageconnection::where('uuid', '=', $uuid)->first();
        $this->prepareConnection($storageconnection);

        $value = $key;
        $dbalDataType = $this->variableTypes();        
    
        $schema = DB::connection($storageconnection->title)->getDoctrineSchemaManager();
        $connectionName = $storageconnection->title;

        $tables = $schema->listTableNames();
        $tableName = $tables[$key];    
        
         
        $columns = $schema->listTableColumns($tables[$key]);
        

        $matchedColumns = [];

        foreach ($selectedArray as $selectedColumn) {
            if (array_key_exists($selectedColumn, $columns)) {
                $matchedColumns[$selectedColumn] = $columns[$selectedColumn];
            }
        }

        // dd($columns, $selected, $matchedColumns);
        // dd($matchedColumns);

        $jsonData = [];
         foreach($matchedColumns as $column){
            $attrtibutes = $column->toArray();
            $columnNames[$key] = $column->getType();           
            if(strtolower($attrtibutes['name'])=='id'){
                $jsonData[strtolower($attrtibutes['name'])] = [                
                    'dataType' => $dbalDataType[get_class($columnNames[$key])],
                    'length' => $attrtibutes['length'] === 'NULL' ? null : ($attrtibutes['length'] === 191 ? 255 : $attrtibutes['length']),
                    'isPrimaryKey' => true,
                'miscellaneous' => [
                    'unsigned' => $attrtibutes['unsigned'],
                    'nullable' => $attrtibutes['notnull'] === true ? false : true,
                    'default' => $attrtibutes['default'] === 'NULL' ? null : $attrtibutes['default'],
                    'comment' => $attrtibutes['comment'] === 'NULL' ? null : $attrtibutes['comment']
                ],
                ];

            }else{
                $jsonData[strtolower($attrtibutes['name'])] = [                
                    'dataType' => $attrtibutes['length'] === 1 ? 'char' : $dbalDataType[get_class($columnNames[$key])],
                    'length' => $attrtibutes['length'] === 'NULL' ? null : ($attrtibutes['length'] === 191 ? 255 : $attrtibutes['length']),
                    'isPrimaryKey' => false,
                'miscellaneous' => [
                    'unsigned' => $attrtibutes['unsigned'],
                    'nullable' => $attrtibutes['notnull'] === true ? false : true,
                    'default' => $attrtibutes['default'] === 'NULL' ? null : $attrtibutes['default'],
                    'comment' => $attrtibutes['comment'] === 'NULL' ? null : $attrtibutes['comment']
                ],
                ];

            }

src/resources/views/structures/create.blade.php
<x-sg-master>
    <x-sg-card>
        <x-slot name="heading">
            {{ __('Structure') }}
        </x-slot>
        <x-slot name="body">
            <x-sg-alert-errors :errors="$errors" />
            <form action="{{ route('structures.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="row">
                {{--relationalFields--}}

                    <!-- column -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="columnInput">{{ __('Column') }}</x-sg-label>
        <x-sg-text type="text" id="columnInput" name="column" :value="old('column')" placeholder="" />
        <x-sg-alert-errors name="column" />
    </div>
</div>

<!-- data_type -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="data_typeInput">{{ __('Data Type') }}</x-sg-label>
        <x-sg-text type="text" id="data_typeInput" name="data_type" :value="old('data_type')" placeholder="" />
        <x-sg-alert-errors name="data_type" />
    </div>
</div>

<!-- lenght -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="lenghtInput">{{ __('Lenght') }}</x-sg-label>
        <x-sg-text type="text" id="lenghtInput" name="lenght" :value="old('lenght')" placeholder="" />
        <x-sg-alert-errors name="lenght" />
    </div>
</div>

<!-- collation -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="collationInput">{{ __('Collation') }}</x-sg-label>
        <x-sg-text type="text" id="collationInput" name="collation" :value="old('collation')" placeholder="" />
        <x-sg-alert-errors name="collation" />
    </div>
</div>

<!-- attributes -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="attributesInput">{{ __('Attributes') }}</x-sg-label>
        <x-sg-text type="text" id="attributesInput" name="attributes" :value="old('attributes')" placeholder="" />
        <x-sg-alert-errors name="attributes" />
    </div>
</div>

<!-- null -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="nullInput">{{ __('Null') }}</x-sg-label>
        <x-sg-text type="text" id="nullInput" name="null" :value="old('null')" placeholder="" />
        <x-sg-alert-errors name="null" />
    </div>
</div>

<!-- default -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="defaultInput">{{ __('Default') }}</x-sg-label>
        <x-sg-text type="text" id="defaultInput" name="default" :value="old('default')" placeholder="" />
        <x-sg-alert-errors name="default" />
    </div>
</div>

<!-- comment -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="commentInput">{{ __('Comment') }}</x-sg-label>
        <x-sg-text type="text" id="commentInput" name="comment" :value="old('comment')" placeholder="" />
        <x-sg-alert-errors name="comment" />
    </div>
</div>

<!-- extra -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="extraInput">{{ __('Extra') }}</x-sg-label>
        <x-sg-text type="text" id="extraInput" name="extra" :value="old('extra')" placeholder="" />
        <x-sg-alert-errors name="extra" />
    </div>
</div>



                    <div class = "{{$decoration['class']['formfooter']}}" >
                        <x-sg-btn-submit />
                        <x-sg-btn-cancel />
                    </div>
                </div>
            </form>
        </x-slot>
        <x-slot name="cardFooterCenter">
            <x-sg-link-list href="{{route('structures.index')}}" />
        </x-slot>
    </x-sg-card>

@push('css')
{{--pagespecific-css--}}
@endpush

@push('js')
{{--pagespecific-js--}}
@endpush

</x-sg-master>

src/resources/views/structures/edit.blade.php
<x-sg-master>
    <x-sg-card>
        <x-slot name="heading">
            {{ __('Structure') }}
        </x-slot>
        <x-slot name="body">
            <x-sg-alert-errors :errors="$errors" />
            <form action="{{ route('structures.update', $structure->uuid) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PATCH')
                <div class="row">
                    {{--relationalFields--}}
                    <!-- column -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="columnInput">{{ __('Column') }}</x-sg-label>
        <x-sg-text type="text" id="columnInput" name="column" :value="old('column', $structure->column)" placeholder="" />
        <x-sg-alert-errors name="column" />
    </div>
</div>

<!-- data_type -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="data_typeInput">{{ __('Data Type') }}</x-sg-label>
        <x-sg-text type="text" id="data_typeInput" name="data_type" :value="old('data_type', $structure->data_type)" placeholder="" />
        <x-sg-alert-errors name="data_type" />
    </div>
</div>

<!-- lenght -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="lenghtInput">{{ __('Lenght') }}</x-sg-label>
        <x-sg-text type="text" id="lenghtInput" name="lenght" :value="old('lenght', $structure->lenght)" placeholder="" />
        <x-sg-alert-errors name="lenght" />
    </div>
</div>

<!-- collation -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="collationInput">{{ __('Collation') }}</x-sg-label>
        <x-sg-text type="text" id="collationInput" name="collation" :value="old('collation', $structure->collation)" placeholder="" />
        <x-sg-alert-errors name="collation" />
    </div>
</div>

<!-- attributes -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="attributesInput">{{ __('Attributes') }}</x-sg-label>
        <x-sg-text type="text" id="attributesInput" name="attributes" :value="old('attributes', $structure->attributes)" placeholder="" />
        <x-sg-alert-errors name="attributes" />
    </div>
</div>

<!-- null -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="nullInput">{{ __('Null') }}</x-sg-label>
        <x-sg-text type="text" id="nullInput" name="null" :value="old('null', $structure->null)" placeholder="" />
        <x-sg-alert-errors name="null" />
    </div>
</div>

<!-- default -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="defaultInput">{{ __('Default') }}</x-sg-label>
        <x-sg-text type="text" id="defaultInput" name="default" :value="old('default', $structure->default)" placeholder="" />
        <x-sg-alert-errors name="default" />
    </div>
</div>

<!-- comment -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="commentInput">{{ __('Comment') }}</x-sg-label>
        <x-sg-text type="text" id="commentInput" name="comment" :value="old('comment', $structure->comment)" placeholder="" />
        <x-sg-alert-errors name="comment" />
    </div>
</div>

<!-- extra -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="extraInput">{{ __('Extra') }}</x-sg-label>
        <x-sg-text type="text" id="extraInput" name="extra" :value="old('extra', $structure->extra)" placeholder="" />
        <x-sg-alert-errors name="extra" />
    </div>
</div>



                    <div class = "{{$decoration['class']['formfooter']}}" >
                        <x-sg-btn-submit />
                        <x-sg-btn-cancel />
                    </div>
                </div>
            </form>
        </x-slot>
        <x-slot name="cardFooterCenter">
            <x-sg-link-list href="{{route('structures.index')}}" />
        </x-slot>
    </x-sg-card>
@push('css')
{{--pagespecific-css--}}
@endpush

@push('js')
{{--pagespecific-js--}}
@endpush

</x-sg-master>

src/resources/views/structures/editablestructure.blade.php
<x-sg-master>
    <x-sg-card>
        <x-slot name="heading">
            {{ __('Editable Structure (' . $table . ')') }}
        </x-slot>
        <x-slot name="body">
            <x-sg-alert-message :message="session('success')" type="success" />
            <form action="{{route('editablestructure.store')}}" method="post">
                @csrf
                <x-sg-table type="basic"  id="structureDatatable">
                    <x-sg-thead>
                        <tr>
                            <th>{{ __('SL') }}</th>
                            <th>{{ __('Column') }}</th>
                            <th>{{ __('Alease') }}</th>
                            <th>{{ __('Data Type') }}</th>
                            <th>{{ __('Lenght') }}</th>
                            <th>{{ __('Default') }}</th>
                            <th>{{ __('Unsigned') }}</th>
                            <th>{{ __('Comment') }}</th>
                            <th>{{ __('Not null') }}</th>
                            <th>{{'Precision'}}</th>						
                            <th>{{'Scale'}}</th>						
                            <th>{{'Autoincrement'}}</th>						
                            <th>{{'ColumnDefinition'}}</th>
                            
                        </tr>
                    </x-sg-thead>
                    <x-sg-tbody>
                        @php                  
                            $counter = 0;                       
                        @endphp
                        @foreach ($columns as $index=>$column)
                        @php
                            $attr = $column->toArray();
                        @endphp
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>
                                {{$index}}
                                <input type="hidden" name="column[]" value="{{ $index }}">
                            </td>
                            <td>
                               
                                <input type="text" name="aleas[]" value="{{  implode(' ', array_map('ucfirst', explode('_',$index))) }}" class="form-control">
                            </td>
                            <td>{{$types[$counter]}}</td>
                            <td>
                                <input type="text" name="length[]" class="form-control" value="{{$attr['length']}}">
                            </td>
                             <td>
                                <input type="checkbox" name="default[]" class="form-control" value="{{$attr['default']?'Y':'N'}}">
                            </td>
                             <td>
                                <input type="checkbox" name="unsigned[]" class="form-control" value="{{$attr['unsigned']?'Y':'N'}}">
                            </td>
                            <td>
                                <input type="text" name="comment[]" class="form-control" value="{{$attr['comment']}}">
                            </td>
                            <td>
                                <input type="checkbox" name="notnull[]" class="form-control" value="{{$attr['notnull']?'Y':'N'}}">
                            </td> 
                            <td>
                                <input type="text" name="precision[]" class="form-control" value="{{$attr['precision']}}">
                            </td> 
                            <td>
                                <input type="text" name="scale[]" class="form-control" value="{{$attr['scale']}}">
                            </td>
                            <td>
                                <input type="checkbox" name="autoincrement[]" class="form-control" value="{{$attr['autoincrement']?'Y':'N'}}">
                            </td>
                            <td>
                                <input type="text" name="columnDefinition[]" class="form-control" value="{{$attr['columnDefinition']}}">
                            </td>											
                        </tr>
                        @php
                            $counter++
                        @endphp
                        @endforeach
                    </x-sg-tbody>
                </x-sg-table>

                <div class = "{{$decoration['class']['formfooter']}}" >
                    <x-sg-btn-submit />
                    <x-sg-btn-cancel />
                </div>
            </form>
        </x-slot>
        <x-slot name="cardFooterCenter">

            <x-sg-link-create href="{{route('structures.create')}}" />

        </x-slot>
    </x-sg-card>



@push('js')


<script>
   $(document).ready(function() {
        $('#structureDatatable').DataTable({
            buttons: [
                {
                    extend: 'colvis',
                    text: '<i class="icon-grid3"></i>',
                    className: 'btn bg-indigo-400 btn-icon dropdown-toggle'
                }
            ],
            stateSave: false,
            columnDefs: [
                {
                    targets: 0,
                    visible: true
                }
            ]
        });
    });
</script>
@endpush

</x-sg-master>
{{-- "name" => "ID"
"type" => Doctrine\DBAL\Types\IntegerType {#1454}
"default" => null
"notnull" => true
"length" => null
"precision" => 10
"scale" => 0
"fixed" => false
"unsigned" => false
"autoincrement" => false
"columnDefinition" => null
"comment" => null 
{{ isset($coveringletter->source_branch) ? $coveringletter->source_branch : null }}
--}}

src/resources/views/structures/show.blade.php
<x-sg-master>
    <x-sg-card>
        <x-slot name="heading">
            {{ __('Structure (' . $table . ')') }}
        </x-slot>
        <x-slot name="body">
            <p><b>{{ __('Column') }} : </b> {{ $structure->column }}</p>
			<p><b>{{ __('Data Type') }} : </b> {{ $structure->data_type }}</p>
			<p><b>{{ __('Lenght') }} : </b> {{ $structure->lenght }}</p>
			<p><b>{{ __('Collation') }} : </b> {{ $structure->collation }}</p>
			<p><b>{{ __('Attributes') }} : </b> {{ $structure->attributes }}</p>
			<p><b>{{ __('Null') }} : </b> {{ $structure->null }}</p>
			<p><b>{{ __('Default') }} : </b> {{ $structure->default }}</p>
			<p><b>{{ __('Comment') }} : </b> {{ $structure->comment }}</p>
			<p><b>{{ __('Extra') }} : </b> {{ $structure->extra }}</p>
			
            {{--othersInfo--}}
        </x-slot>
        <x-slot name="cardFooterCenter">
            <x-sg-link-create href="{{route('structures.index')}}" />
            <x-sg-link-list href="{{route('structures.index')}}" />
            <x-sg-link-edit href="{{route('structures.edit',$structure->uuid)}}" />
            <x-sg-link-history uuid="{{$structure->uuid}}" api="/api/structures-histories-list" />
        </x-slot>
    </x-sg-card>

@push('css')
{{--pagespecific-css--}}
@endpush

@push('js')
{{--pagespecific-js--}}
@endpush
</x-sg-master>