src/routes/web.php
<?php 
use Illuminate\Support\Facades\Route;
use Genie\Schematojson\Schema\Http\Controllers\SchemaSheetController;
use Genie\Schematojson\Schema\Http\Controllers\StoragetypeController;
use Genie\Schematojson\Schema\Http\Controllers\TableController;
use Genie\Schematojson\Schema\Http\Controllers\StructureController;


use Genie\Schematojson\Schema\Http\Controllers\StorageconnectionController;
//use namespace

Route::group(['middleware' => 'web'], function () {
	Route::resource('storagetypes', StoragetypeController::class);
	Route::resource('storageconnections', StorageconnectionController::class);
	Route::resource('tables', TableController::class);
	Route::resource('json_structures', StructureController::class);

//Place your route here
Route::post('createJson', [SchemaSheetController::class, 'create'])->name('create_json');
Route::post('store', [SchemaSheetController::class, 'store'])->name('json_store');
Route::post('select', [SchemaSheetController::class, 'selectTable'])->name('json_select');
// Route::get('connect/{datasource}', [StorageconnectionController::class, 'connect'])->name('inputSpreadSheet');
Route::get('connect/{uuid}', [StorageconnectionController::class, 'connect'])->name('storageconnection');

Route::get('/columns/{key}/{uuid}',[StructureController::class, 'structure'])->name('structure');
Route::get('/editablestructure/{key}/{uuid}',[StructureController::class, 'editablestructure'])->name('editablestructure');
Route::post('/editablestructure',[StructureController::class, 'editablestructurestore'])->name('editablestructure.store');
Route::get('/json-structure/{key}/{uuid}',[StructureController::class, 'jsonStructure'])->name('structures.json');
Route::get('/table/{key}',[TableController::class, 'tables'])->name('table');
Route::get('/selectedstructure/{key}/{uuid}',[StructureController::class, 'selectedStructure'])->name('selectedstructure');
Route::post('/selectedStructureJson',[StructureController::class, 'selectedStructureJson'])->name('selectedStructure.json');
Route::get('/pdf-structure/{key}/{uuid}',[StructureController::class, 'pdfStructure'])->name('structure.pdf');
Route::post('oracle/input-spreadsheet',[SchemaSheetController::class, 'inputSpreadsheetForStore'])->name('input_json_to_excel');
Route::post('oracle/select-table',[SchemaSheetController::class, 'selectSheetForStore'])->name('selectSheet_json_to_excel');
Route::post('oracle/store-excel',[SchemaSheetController::class, 'storeExcel'])->name('store_json_to_excel');
Route::post('oracle/include-columns',[StructureController::class, 'includeColumn'])->name('include_column_json');




});

src/Http/Controllers/Api/StoragetypeController.php
<?php

namespace Genie\Schematojson\Schema\Http\Controllers\Api;

class StoragetypeController extends StoragetypeBaseController
{

}

src/Http/Controllers/StoragetypeController.php
<?php

namespace Genie\Schematojson\Schema\Http\Controllers;

use Genie\Schematojson\Schema\Http\Requests\StoragetypeRequest;
use Genie\Schematojson\Schema\Models\Storagetype;
use Illuminate\Database\QueryException;
use Illuminate\Support\Str;

class StoragetypeController extends StoragetypeBaseController
{
    public function store(StoragetypeRequest $request)
    {
        try {
            $storagetype = Storagetype::create(['uuid'=> (string)Str::uuid()] + $request->all());
            //handle relationship store
            return redirect()->route('storagetypes.index')
                ->withSuccess(__('Successfully Created'));
        } catch (\Exception | QueryException $e) {
            \Log::channel('pondit')->error($e->getMessage());
            return redirect()->back()->withInput()->withErrors(
                config('app.env') == 'production' ? __('Somethings Went Wrong') : $e->getMessage()
            );
        }
    }
}

src/resources/views/storagetypes/create.blade.php
<x-sg-master>
    <x-sg-card>
        <x-slot name="heading">
            {{ __('StorageType') }}
        </x-slot>
        <x-slot name="body">
            <x-sg-alert-errors :errors="$errors" />
            <form action="{{ route('storagetypes.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="row">
                {{--relationalFields--}}

                    <!-- title -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="titleInput">{{ __('Title') }}</x-sg-label>
        <x-sg-text type="text" id="titleInput" name="title" :value="old('title')" placeholder="" />
        <x-sg-alert-errors name="title" />
    </div>
</div>

<!-- type -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="typeInput">{{ __('Type') }}</x-sg-label>
        <!-- <x-sg-text type="text" id="typeInput" name="type" :value="old('type')" placeholder="" /> -->
        @php
            $types = ["SQL", "NoSQL", "SASS"];
        @endphp

        <select name="type" class="form-control form-control-lg">
			@foreach($types as $type)
            <option>{{ $type }}</option>
            @endforeach
		</select>
        <x-sg-alert-errors name="type" />
    </div>
</div>

<!-- description -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="descriptionInput">{{ __('Description') }}</x-sg-label>
        <x-sg-text type="text" id="descriptionInput" name="description" :value="old('description')" placeholder="" />
        <x-sg-alert-errors name="description" />
    </div>
</div>



                    <div class = "{{$decoration['class']['formfooter']}}" >
                        <x-sg-btn-submit />
                        <x-sg-btn-cancel />
                    </div>
                </div>
            </form>
        </x-slot>
        <x-slot name="cardFooterCenter">
            <x-sg-link-list href="{{route('storagetypes.index')}}" />
        </x-slot>
    </x-sg-card>

@push('css')
{{--pagespecific-css--}}
@endpush

@push('js')
{{--pagespecific-js--}}
@endpush

</x-sg-master>

src/resources/views/storagetypes/edit.blade.php
<x-sg-master>
    <x-sg-card>
        <x-slot name="heading">
            {{ __('StorageType') }}
        </x-slot>
        <x-slot name="body">
            <x-sg-alert-errors :errors="$errors" />
            <form action="{{ route('storagetypes.update', $storagetype->uuid) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PATCH')
                <div class="row">
                    {{--relationalFields--}}
                    <!-- title -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="titleInput">{{ __('Title') }}</x-sg-label>
        <x-sg-text type="text" id="titleInput" name="title" :value="old('title', $storagetype->title)" placeholder="" />
        <x-sg-alert-errors name="title" />
    </div>
</div>

<!-- type -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="typeInput">{{ __('Type') }}</x-sg-label>
        @php
            $types = ["SQL", "NoSQL", "SASS"];
            $selectedType = $storagetype->type;
        @endphp
        <select name="type" class="form-control form-control-lg">
            @foreach ($types as $type)
                <option value="{{ $type }}" @if ($type == $selectedType) selected @endif>{{ $type }}</option>
            @endforeach
        </select>


        {{-- <x-sg-text type="text" id="typeInput" name="type" :value="old('type', $storagetype->type)" placeholder="" /> --}}

        <x-sg-alert-errors name="type" />
    </div>
</div>

<!-- description -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="descriptionInput">{{ __('Description') }}</x-sg-label>
        <x-sg-text type="text" id="descriptionInput" name="description" :value="old('description', $storagetype->description)" placeholder="" />
        <x-sg-alert-errors name="description" />
    </div>
</div>



                    <div class = "{{$decoration['class']['formfooter']}}" >
                        <x-sg-btn-submit />
                        <x-sg-btn-cancel />
                    </div>
                </div>
            </form>
        </x-slot>
        <x-slot name="cardFooterCenter">
            <x-sg-link-list href="{{route('storagetypes.index')}}" />
        </x-slot>
    </x-sg-card>
@push('css')
{{--pagespecific-css--}}
@endpush

@push('js')
{{--pagespecific-js--}}
@endpush

</x-sg-master>

src/resources/views/storagetypes/index.blade.php
<x-sg-master>
    <x-sg-card>
        <x-slot name="heading">
            {{ __('StorageType') }}
        </x-slot>
        <x-slot name="body">
            <x-sg-alert-message :message="session('success')" type="success" />
            <x-sg-table type="basic"  id="storagetypeDatatable">
                <x-sg-thead>
                    <tr>
                        <th>{{ __('SL') }}</th>
                            						<th>{{ __('Title') }}</th>
						<th>{{ __('Type') }}</th>

                        <th>{{ __('Actions' )}}</th>
                    </tr>
                </x-sg-thead>
                <x-sg-tbody>
                    @foreach ($storagetypes as $storagetype)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        						<td>{{ $storagetype->title }}</td>
						<td>{{ $storagetype->type }}</td>

                        <td>
                            <x-sg-link-show href="{{route('storagetypes.show', $storagetype->uuid)}}" />
                            <x-sg-link-edit href="{{route('storagetypes.edit', $storagetype->uuid)}}" />
                            <x-sg-btn-delete action="{{route('storagetypes.destroy', $storagetype->uuid)}}" method="post" />
                            <x-sg-link-history uuid="{{ $storagetype->uuid }}"  api="/api/storagetype-histories-list" />
                        </td>
                    </tr>
                    @endforeach
                </x-sg-tbody>
            </x-sg-table>
        </x-slot>
        <x-slot name="cardFooterCenter">

            <x-sg-link-create href="{{route('storagetypes.create')}}" />

        </x-slot>
    </x-sg-card>



@push('js')


<script>
   $(document).ready(function() {
        $('#storagetypeDatatable').DataTable({
            buttons: [
                {
                    extend: 'colvis',
                    text: '<i class="icon-grid3"></i>',
                    className: 'btn bg-indigo-400 btn-icon dropdown-toggle'
                }
            ],
            stateSave: false,
            columnDefs: [
                {
                    targets: 0,
                    visible: true
                }
            ]
        });
    });
</script>
@endpush

</x-sg-master>

src/resources/views/storagetypes/show.blade.php
<x-sg-master>
    <x-sg-card>
        <x-slot name="heading">
            {{ __('StorageType') }}
        </x-slot>
        <x-slot name="body">
            <p><b>{{ __('Title') }} : </b> {{ $storagetype->title }}</p>
			<p><b>{{ __('Type') }} : </b> {{ $storagetype->type }}</p>
			<p><b>{{ __('Description') }} : </b> {{ $storagetype->description }}</p>
			
            {{--othersInfo--}}
        </x-slot>
        <x-slot name="cardFooterCenter">
            <x-sg-link-create href="{{route('storagetypes.index')}}" />
            <x-sg-link-list href="{{route('storagetypes.index')}}" />
            <x-sg-link-edit href="{{route('storagetypes.edit',$storagetype->uuid)}}" />
            <x-sg-link-history uuid="{{$storagetype->uuid}}" api="/api/storagetypes-histories-list" />
        </x-slot>
    </x-sg-card>

@push('css')
{{--pagespecific-css--}}
@endpush

@push('js')
{{--pagespecific-js--}}
@endpush
</x-sg-master>