src/routes/web.php
<?php 
use Illuminate\Support\Facades\Route;
use Genie\Schematojson\Schema\Http\Controllers\SchemaSheetController;
use Genie\Schematojson\Schema\Http\Controllers\StoragetypeController;
use Genie\Schematojson\Schema\Http\Controllers\TableController;
use Genie\Schematojson\Schema\Http\Controllers\StructureController;


use Genie\Schematojson\Schema\Http\Controllers\StorageconnectionController;
//use namespace

Route::group(['middleware' => 'web'], function () {
	Route::resource('storagetypes', StoragetypeController::class);
	Route::resource('storageconnections', StorageconnectionController::class);
	Route::resource('tables', TableController::class);
	Route::resource('json_structures', StructureController::class);

//Place your route here
Route::post('createJson', [SchemaSheetController::class, 'create'])->name('create_json');
Route::post('store', [SchemaSheetController::class, 'store'])->name('json_store');
Route::post('select', [SchemaSheetController::class, 'selectTable'])->name('json_select');
// Route::get('connect/{datasource}', [StorageconnectionController::class, 'connect'])->name('inputSpreadSheet');
Route::get('connect/{uuid}', [StorageconnectionController::class, 'connect'])->name('storageconnection');

Route::get('/columns/{key}/{uuid}',[StructureController::class, 'structure'])->name('structure');
Route::get('/editablestructure/{key}/{uuid}',[StructureController::class, 'editablestructure'])->name('editablestructure');
Route::post('/editablestructure',[StructureController::class, 'editablestructurestore'])->name('editablestructure.store');
Route::get('/json-structure/{key}/{uuid}',[StructureController::class, 'jsonStructure'])->name('structures.json');
Route::get('/table/{key}',[TableController::class, 'tables'])->name('table');
Route::get('/selectedstructure/{key}/{uuid}',[StructureController::class, 'selectedStructure'])->name('selectedstructure');
Route::post('/selectedStructureJson',[StructureController::class, 'selectedStructureJson'])->name('selectedStructure.json');
Route::get('/pdf-structure/{key}/{uuid}',[StructureController::class, 'pdfStructure'])->name('structure.pdf');
Route::post('oracle/input-spreadsheet',[SchemaSheetController::class, 'inputSpreadsheetForStore'])->name('input_json_to_excel');
Route::post('oracle/select-table',[SchemaSheetController::class, 'selectSheetForStore'])->name('selectSheet_json_to_excel');
Route::post('oracle/store-excel',[SchemaSheetController::class, 'storeExcel'])->name('store_json_to_excel');
Route::post('oracle/include-columns',[StructureController::class, 'includeColumn'])->name('include_column_json');




});

src/Http/Controllers/TableController.php
<?php

namespace Genie\Schematojson\Schema\Http\Controllers;
use App\Http\Controllers\Controller;
use Genie\Schematojson\Schema\Http\Requests\TableRequest;
use Genie\Schematojson\Schema\Models\Table;
use Illuminate\Database\QueryException;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
class TableController extends TableBaseController
{
    public function index()
    {
        
        $schema = DB::connection()->getDoctrineSchemaManager();
        $tables = $schema->listTableNames();
        // dd($tables);
        $columns = [];
        foreach($tables as $key => $table){
            $columns[] =$schema->listTableColumns($tables[$key]);
        }
        // dd($tables[0]);
        $columns = $schema->listTableColumns($tables[0]);
        // dd($columns);
      
        return view('schema::tables.index', compact('tables'));
    }

    public function tables($key)
    {

        $value = $key;
        $schema = DB::connection()->getDoctrineSchemaManager();
        $tables = $schema->listTableNames([$key]);
        dd($tables);
        // dd($key);


        return view('schema::tables.index', compact('tables','value'));
    }


    public function store(TableRequest $request)
    {
        try {
            $table = Table::create(['uuid'=>(string) Str::uuid()] + $request->all());
            //handle relationship store
            return redirect()->route('tables.index')
                ->withSuccess(__('Successfully Created'));
        } catch (\Exception | QueryException $e) {
            \Log::channel('pondit')->error($e->getMessage());
            return redirect()->back()->withInput()->withErrors(
                config('app.env') == 'production' ? __('Somethings Went Wrong') : $e->getMessage()
            );
        }
    }

}

src/resources/views/tables/create.blade.php
<x-sg-master>
    <x-sg-card>
        <x-slot name="heading">
            {{ __('Tables') }}
        </x-slot>
        <x-slot name="body">
            <x-sg-alert-errors :errors="$errors" />
            <form action="{{ route('tables.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="row">
                {{--relationalFields--}}

                    <!-- title -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="titleInput">{{ __('Title') }}</x-sg-label>
        <x-sg-text type="text" id="titleInput" name="title" :value="old('title')" placeholder="" />
        <x-sg-alert-errors name="title" />
    </div>
</div>

<!-- rows -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="rowsInput">{{ __('Rows') }}</x-sg-label>
        <x-sg-text type="text" id="rowsInput" name="rows" :value="old('rows')" placeholder="" />
        <x-sg-alert-errors name="rows" />
    </div>
</div>

<!-- type -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="typeInput">{{ __('Type') }}</x-sg-label>
        <x-sg-text type="text" id="typeInput" name="type" :value="old('type')" placeholder="" />
        <x-sg-alert-errors name="type" />
    </div>
</div>

<!-- collation -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="collationInput">{{ __('Collation') }}</x-sg-label>
        <x-sg-text type="text" id="collationInput" name="collation" :value="old('collation')" placeholder="" />
        <x-sg-alert-errors name="collation" />
    </div>
</div>

<!-- data length -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="data lengthInput">{{ __('Data length') }}</x-sg-label>
        <x-sg-text type="text" id="data lengthInput" name="data_length" :value="old('data length')" placeholder="" />
        <x-sg-alert-errors name="data length" />
    </div>
</div>

<!-- index length -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="index lengthInput">{{ __('Index length') }}</x-sg-label>
        <x-sg-text type="text" id="index lengthInput" name="index_length" :value="old('index length')" placeholder="" />
        <x-sg-alert-errors name="index length" />
    </div>
</div>

<!-- data free -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="data freeInput">{{ __('Data free') }}</x-sg-label>
        <x-sg-text type="text" id="data freeInput" name="data_free" :value="old('data free')" placeholder="" />
        <x-sg-alert-errors name="data free" />
    </div>
</div>

<!-- auto increment -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="auto incrementInput">{{ __('Auto increment') }}</x-sg-label>
        <x-sg-text type="text" id="auto incrementInput" name="auto_increment" :value="old('auto increment')" placeholder="" />
        <x-sg-alert-errors name="auto increment" />
    </div>
</div>

<!-- comment -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="commentInput">{{ __('Comment') }}</x-sg-label>
        <x-sg-text type="text" id="commentInput" name="comment" :value="old('comment')" placeholder="" />
        <x-sg-alert-errors name="comment" />
    </div>
</div>



                    <div class = "{{$decoration['class']['formfooter']}}" >
                        <x-sg-btn-submit />
                        <x-sg-btn-cancel />
                    </div>
                </div>
            </form>
        </x-slot>
        <x-slot name="cardFooterCenter">
            <x-sg-link-list href="{{route('tables.index')}}" />
        </x-slot>
    </x-sg-card>

@push('css')
{{--pagespecific-css--}}
@endpush

@push('js')
{{--pagespecific-js--}}
@endpush

</x-sg-master>

src/resources/views/tables/edit.blade.php
<x-sg-master>
    <x-sg-card>
        <x-slot name="heading">
            {{ __('Table') }}
        </x-slot>
        <x-slot name="body">
            <x-sg-alert-errors :errors="$errors" />
            <form action="{{ route('tables.update', $table->uuid) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PATCH')
                <div class="row">
                    {{--relationalFields--}}
                    <!-- title -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="titleInput">{{ __('Title') }}</x-sg-label>
        <x-sg-text type="text" id="titleInput" name="title" :value="old('title', $table->title)" placeholder="" />
        <x-sg-alert-errors name="title" />
    </div>
</div>

<!-- rows -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="rowsInput">{{ __('Rows') }}</x-sg-label>
        <x-sg-text type="text" id="rowsInput" name="rows" :value="old('rows', $table->rows)" placeholder="" />
        <x-sg-alert-errors name="rows" />
    </div>
</div>

<!-- type -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="typeInput">{{ __('Type') }}</x-sg-label>
        <x-sg-text type="text" id="typeInput" name="type" :value="old('type', $table->type)" placeholder="" />
        <x-sg-alert-errors name="type" />
    </div>
</div>

<!-- collation -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="collationInput">{{ __('Collation') }}</x-sg-label>
        <x-sg-text type="text" id="collationInput" name="collation" :value="old('collation', $table->collation)" placeholder="" />
        <x-sg-alert-errors name="collation" />
    </div>
</div>

<!-- data length -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="data lengthInput">{{ __('Data length') }}</x-sg-label>
        <x-sg-text type="text" id="data lengthInput" name="data length" :value="old('data length', $table->data length)" placeholder="" />
        <x-sg-alert-errors name="data length" />
    </div>
</div>

<!-- index length -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="index lengthInput">{{ __('Index length') }}</x-sg-label>
        <x-sg-text type="text" id="index lengthInput" name="index length" :value="old('index length', $table->index length)" placeholder="" />
        <x-sg-alert-errors name="index length" />
    </div>
</div>

<!-- data free -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="data freeInput">{{ __('Data free') }}</x-sg-label>
        <x-sg-text type="text" id="data freeInput" name="data free" :value="old('data free', $table->data free)" placeholder="" />
        <x-sg-alert-errors name="data free" />
    </div>
</div>

<!-- auto increment -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="auto incrementInput">{{ __('Auto increment') }}</x-sg-label>
        <x-sg-text type="text" id="auto incrementInput" name="auto increment" :value="old('auto increment', $table->auto increment)" placeholder="" />
        <x-sg-alert-errors name="auto increment" />
    </div>
</div>

<!-- comment -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="commentInput">{{ __('Comment') }}</x-sg-label>
        <x-sg-text type="text" id="commentInput" name="comment" :value="old('comment', $table->comment)" placeholder="" />
        <x-sg-alert-errors name="comment" />
    </div>
</div>



                    <div class = "{{$decoration['class']['formfooter']}}" >
                        <x-sg-btn-submit />
                        <x-sg-btn-cancel />
                    </div>
                </div>
            </form>
        </x-slot>
        <x-slot name="cardFooterCenter">
            <x-sg-link-list href="{{route('tables.index')}}" />
        </x-slot>
    </x-sg-card>
@push('css')
{{--pagespecific-css--}}
@endpush

@push('js')
{{--pagespecific-js--}}
@endpush

</x-sg-master>

src/resources/views/tables/index.blade.php
<x-sg-master>
    <x-sg-card>
        <x-slot name="heading">
            {{ __('Tables') }}
        </x-slot>
        <x-slot name="body">
            <x-sg-alert-message :message="session('success')" type="success" />
            <x-sg-table type="basic"  id="tableDatatable">
                <x-sg-thead>
                    <tr>
                        <th>{{ __('SL') }}</th>
                        <th>{{ __('Title') }}</th>
                        <th>{{ __('Actions' )}}</th>
                    </tr>
                </x-sg-thead>
                <x-sg-tbody>
                    @foreach ($tables as $key=>$table)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $table }}</td>
						
                        <td>
                            <x-sg-link-show href="{{route('structure', [$key, $uuid])}}" />
                            <a class="btn btn-sm bg-grey-800 border-2 border-grey-800 btn-icon rounded-round legitRipple shadow mr-1" href="{{route('structures.json', [$key, $uuid] )}}">
                                <i class="icon-file-css2"></i></a>
                            <x-sg-link-edit href="{{route('editablestructure',  [$key, $uuid])}}" />
                            <a class="btn btn-sm bg-pink-800 border-2 border-pink-800 btn-icon rounded-round legitRipple shadow mr-1" href="{{route('selectedstructure',  [$key, $uuid])}}">
                                <i class="icon-file-check2"></i></a>
                            <x-sg-link-pdf href="{{route('structure.pdf',  [$key, $uuid])}}" />

                          
                        </td>
                    </tr>
                    @endforeach
                </x-sg-tbody>
            </x-sg-table>
        </x-slot>
        <x-slot name="cardFooterCenter">

            <x-sg-link-create href="{{route('tables.create')}}" />

        </x-slot>
    </x-sg-card>



@push('js')


<script>
   $(document).ready(function() {
        $('#tableDatatable').DataTable({
            buttons: [
                {
                    extend: 'colvis',
                    text: '<i class="icon-grid3"></i>',
                    className: 'btn bg-indigo-400 btn-icon dropdown-toggle'
                }
            ],
            stateSave: false,
            columnDefs: [
                {
                    targets: 0,
                    visible: true
                }
            ]
        });
    });
</script>
@endpush

</x-sg-master>

src/resources/views/tables/show.blade.php
<x-sg-master>
    <x-sg-card>
        <x-slot name="heading">
            {{ __('Table') }}
        </x-slot>
        <x-slot name="body">
            <p><b>{{ __('Title') }} : </b> {{ $table->title }}</p>
			<p><b>{{ __('Rows') }} : </b> {{ $table->rows }}</p>
			<p><b>{{ __('Type') }} : </b> {{ $table->type }}</p>
			<p><b>{{ __('Collation') }} : </b> {{ $table->collation }}</p>
			<p><b>{{ __('Data length') }} : </b> {{ $table->data length }}</p>
			<p><b>{{ __('Index length') }} : </b> {{ $table->index length }}</p>
			<p><b>{{ __('Data free') }} : </b> {{ $table->data free }}</p>
			<p><b>{{ __('Auto increment') }} : </b> {{ $table->auto increment }}</p>
			<p><b>{{ __('Comment') }} : </b> {{ $table->comment }}</p>
			
            {{--othersInfo--}}
        </x-slot>
        <x-slot name="cardFooterCenter">
            <x-sg-link-create href="{{route('tables.index')}}" />
            <x-sg-link-list href="{{route('tables.index')}}" />
            <x-sg-link-edit href="{{route('tables.edit',$table->uuid)}}" />
            <x-sg-link-history uuid="{{$table->uuid}}" api="/api/tables-histories-list" />
        </x-slot>
    </x-sg-card>

@push('css')
{{--pagespecific-css--}}
@endpush

@push('js')
{{--pagespecific-js--}}
@endpush
</x-sg-master>