src/routes/web.php
<?php 
use Illuminate\Support\Facades\Route;
use Genie\Schematojson\Schema\Http\Controllers\SchemaSheetController;
use Genie\Schematojson\Schema\Http\Controllers\StoragetypeController;
use Genie\Schematojson\Schema\Http\Controllers\TableController;
use Genie\Schematojson\Schema\Http\Controllers\StructureController;


use Genie\Schematojson\Schema\Http\Controllers\StorageconnectionController;
//use namespace

Route::group(['middleware' => 'web'], function () {
	Route::resource('storagetypes', StoragetypeController::class);
	Route::resource('storageconnections', StorageconnectionController::class);
	Route::resource('tables', TableController::class);
	Route::resource('json_structures', StructureController::class);

//Place your route here
Route::post('createJson', [SchemaSheetController::class, 'create'])->name('create_json');
Route::post('store', [SchemaSheetController::class, 'store'])->name('json_store');
Route::post('select', [SchemaSheetController::class, 'selectTable'])->name('json_select');
// Route::get('connect/{datasource}', [StorageconnectionController::class, 'connect'])->name('inputSpreadSheet');
Route::get('connect/{uuid}', [StorageconnectionController::class, 'connect'])->name('storageconnection');

Route::get('/columns/{key}/{uuid}',[StructureController::class, 'structure'])->name('structure');
Route::get('/editablestructure/{key}/{uuid}',[StructureController::class, 'editablestructure'])->name('editablestructure');
Route::post('/editablestructure',[StructureController::class, 'editablestructurestore'])->name('editablestructure.store');
Route::get('/json-structure/{key}/{uuid}',[StructureController::class, 'jsonStructure'])->name('structures.json');
Route::get('/table/{key}',[TableController::class, 'tables'])->name('table');
Route::get('/selectedstructure/{key}/{uuid}',[StructureController::class, 'selectedStructure'])->name('selectedstructure');
Route::post('/selectedStructureJson',[StructureController::class, 'selectedStructureJson'])->name('selectedStructure.json');
Route::get('/pdf-structure/{key}/{uuid}',[StructureController::class, 'pdfStructure'])->name('structure.pdf');
Route::post('oracle/input-spreadsheet',[SchemaSheetController::class, 'inputSpreadsheetForStore'])->name('input_json_to_excel');
Route::post('oracle/select-table',[SchemaSheetController::class, 'selectSheetForStore'])->name('selectSheet_json_to_excel');
Route::post('oracle/store-excel',[SchemaSheetController::class, 'storeExcel'])->name('store_json_to_excel');
Route::post('oracle/include-columns',[StructureController::class, 'includeColumn'])->name('include_column_json');




});

src/Models/Storageconnection.php
<?php

namespace Genie\Schematojson\Schema\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Traits\UserTrackable;


use App\Traits\Historiable;

class Storageconnection extends Model
{
    use UserTrackable;
    use SoftDeletes;
    
    
    use Historiable;
    protected $connection = 'keepmealone';
    protected $table = 'storageconnections';
    protected $guarded = ['id'];
    

    /**
    * Get the route key for the model.
    *
    * @return string
    */
    public function getRouteKeyName()
    {
        return 'uuid';
    }

    ##ELOQUENTRELATIONSHIPMODEL##
}

src/Http/Controllers/Api/StorageconnectionController.php
<?php

namespace Genie\Schematojson\Schema\Http\Controllers\Api;

class StorageconnectionController extends StorageconnectionBaseController
{

}

src/Http/Controllers/StorageconnectionController.php
<?php

namespace Genie\Schematojson\Schema\Http\Controllers;

use Genie\Schematojson\Schema\App\SourceGoogleSpreadsheet;
use Genie\Schematojson\Schema\App\SourceOracle;
use Genie\Schematojson\Schema\App\SourceMySql;

use Genie\Schematojson\Schema\Http\Requests\StorageconnectionRequest;
use Genie\Schematojson\Schema\Models\Storageconnection;
use Illuminate\Database\QueryException;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB;



class StorageconnectionController extends StorageconnectionBaseController
{
    public function connect($uuid)
    {
        
        $storageconnection = Storageconnection::where('uuid', '=', $uuid)->first();
        $datasource = $storageconnection->storagetype_title;
        // dd($datasource);
        $this->prepareConnection($storageconnection);
        // dd($datasource);
        if(is_null($datasource))
        {
            echo 'data source not found';
        }
        if($datasource=='Google-Sheet')
        {
           return (new SourceGoogleSpreadsheet())->connect($storageconnection->title, $uuid);
        }

        if($datasource=='Oracle')
        {
           return (new SourceOracle())->connect($storageconnection->title, $uuid);
        }

        if($datasource=='MySQL')
        {
           return (new SourceMySql())->connect($storageconnection->title, $uuid);
        }
    }

    private function prepareConnection($storageconnection)
    {
        if(strtolower($storageconnection->storagetype_title)==='mysql'){
            $connection = [
                'driver' => strtolower($storageconnection->storagetype_title),
                'host' => $storageconnection->target,
                'port' => '3306',
                'database' => $storageconnection->storage,
                'username' => $storageconnection->client,
                'password' => $storageconnection->secret===null ? '':$storageconnection->secret,
            ];

        }
        if(strtolower($storageconnection->storagetype_title)==='oracle' ||
        strtolower($storageconnection->storagetype_title)==='google-sheet'){
            $connection = [
                'driver' => strtolower($storageconnection->storagetype_title),
                'host' => $storageconnection->target,
                'port' => '1521',
                'database' => $storageconnection->storage,
                'username' => $storageconnection->client,
                'password' => $storageconnection->secret===null ? '':$storageconnection->secret,
            ];
        }
            
        
        // dd($connection);
       
        \Config::set('database.connections.'. $storageconnection->title, $connection);
        // dd(\Config::get('database.connections'));
            
        
    }

    public function store(StorageconnectionRequest $request)
    {
        // dd($request->all());
        try {
            $storageconnection = Storageconnection::create(['uuid'=> (string)Str::uuid()] + $request->all());
            //handle relationship store
            return redirect()->route('storageconnections.index')
                ->withSuccess(__('Successfully Created'));
        } catch (\Exception | QueryException $e) {
            \Log::channel('pondit')->error($e->getMessage());
            return redirect()->back()->withInput()->withErrors(
                config('app.env') == 'production' ? __('Somethings Went Wrong') : $e->getMessage()
            );
        }
    }

   

    // public function jsonStructure2($connection, $uuid){
    //     $storageconnection = Storageconnection::where('uuid', '=', $uuid)->first();
    //     $datasource = $storageconnection->storagetype_title;
    //     $this->prepareConnection($storageconnection);

    //     $schema = DB::connection($connection)->getDoctrineSchemaManager();
    //     $tables = $schema->listTableNames();
    //     // dd($tables);
    //     $columns = [];
    //     foreach($tables as $key => $table){
    //         $columns[] =$schema->listTableColumns($tables[$key]);
    //     }
    //     // dd($tables[0]);
    //     $columns = $schema->listTableColumns($tables[0]);
    //     $value = $key;
    //     $dbalDataType = $this->variableTypes();        
    
    //     // $schema = DB::connection()->getDoctrineSchemaManager();
    //     $connectionName = $connection;

    //     // $engineName = config("database.connections.$connectionName.database");
    //     // $sql = "SELECT value FROM nls_database_parameters WHERE parameter = 'NLS_CHARACTERSET'";

    //     // $result = DB::connection($connectionName)->select($sql);

    //     // if (!empty($result)) {
    //     //     $charsetName = $result[0]->value;
    //     // } else {
    //     //     $charsetName = null;
    //     // }

    //     // $tables = $schema->listTableNames();
    //     // dd($tables);
    //     // $tableName = $tables[$key];    
       
        
         
    //     $columns = $schema->listTableColumns($tables[$key]);
    //     $jsonData = [];
    //      foreach($columns as $column){
    //         $attrtibutes = $column->toArray();
    //         $columnNames[$key] = $column->getType();            
    //         $jsonData[$attrtibutes['name']] = [                
    //             'dataType' => $dbalDataType[get_class($columnNames[$key])],
    //             'length' => $attrtibutes['length'] === 'NULL' ? null : $attrtibutes['length'],
    //             'precision' => $attrtibutes['precision'],
    //             'unsigned' => $attrtibutes['unsigned'] === 'TRUE',
    //             'notnull' => $attrtibutes['notnull'] === 'TRUE',
    //             'autoincrement' => $attrtibutes['autoincrement'],
    //             'columnDefinition' => $attrtibutes['columnDefinition'],
    //             'default' => $attrtibutes['default'] === 'NULL' ? null : $attrtibutes['default'],
    //             'comment' => $attrtibutes['comment'] === 'NULL' ? null : $attrtibutes['comment']
    //         ];
    //        }

    //     $jsonStructure = [
    //         "connection" => $connectionName,
    //         "tableName" =>  "table",
    //         "options" => [
    //             "engine" =>  "ngineName",
    //             "charset" => "charset",
    //         ],
    //         "columns" => $jsonData,
    //     ];    
    //     $response = response()->json($jsonStructure);
    //     $jsonData = $response->getData();
    //     return view('schema::structures.json', compact('response','value','jsonData'));
        
    // }

   
}

src/resources/views/storageconnections/create.blade.php
<x-sg-master>
    <x-sg-card>
        <x-slot name="heading">
            {{ __('StorageConnection') }}
        </x-slot>
        <x-slot name="body">
            <x-sg-alert-errors :errors="$errors" />
            <form action="{{ route('storageconnections.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="row">
                {{--relationalFields--}}

                    <!-- title -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="titleInput">{{ __('Title') }}</x-sg-label>
        <x-sg-text type="text" id="titleInput" name="title" :value="old('title')" placeholder="" />
        <x-sg-alert-errors name="title" />
    </div>
</div>

<!-- storagetype_title -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="storagetype_titleInput">{{ __('Storagetype Title') }}</x-sg-label>
        <x-sg-selecttrio connection="keepmealone" tableName="storagetypes" name="storagetype" />

        {{-- <sg-text type="text" id="storagetype_titleInput" name="storagetype_title" :value="old('storagetype_title')" placeholder="" /> --}}
        <x-sg-alert-errors name="storagetype_title" />
    </div>
</div>

<!-- target -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="targetInput">{{ __('Target') }}</x-sg-label>
        <x-sg-text type="text" id="targetInput" name="target" :value="old('target')" placeholder="" />
        <x-sg-alert-errors name="target" />
    </div>
</div>

<!-- storage -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="storageInput">{{ __('Storage') }}</x-sg-label>
        <x-sg-text type="text" id="storageInput" name="storage" :value="old('storage')" placeholder="" />
        <x-sg-alert-errors name="storage" />
    </div>
</div>

<!-- client -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="clientInput">{{ __('Client') }}</x-sg-label>
        <x-sg-text type="text" id="clientInput" name="client" :value="old('client')" placeholder="" />
        <x-sg-alert-errors name="client" />
    </div>
</div>

<!-- secret -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="secretInput">{{ __('Secret') }}</x-sg-label>
        <x-sg-text type="text" id="secretInput" name="secret" :value="old('secret')" placeholder="" />
        <x-sg-alert-errors name="secret" />
    </div>
</div>

<!-- encription -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="encriptionInput">{{ __('Encription') }}</x-sg-label>
        <x-sg-text type="text" id="encriptionInput" name="encription" :value="old('encription')" placeholder="" />
        <x-sg-alert-errors name="encription" />
    </div>
</div>

<!-- file_path -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="file_pathInput">{{ __('File Path') }}</x-sg-label>
        <x-sg-text type="text" id="file_pathInput" name="file_path" :value="old('file_path')" placeholder="" />
        <x-sg-alert-errors name="file_path" />
    </div>
</div>

<!-- file_content -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="file_contentInput">{{ __('File Content') }}</x-sg-label>
        <x-sg-text type="text" id="file_contentInput" name="file_content" :value="old('file_content')" placeholder="" />
        <x-sg-alert-errors name="file_content" />
    </div>
</div>

<!-- scope -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="scopeInput">{{ __('Scope') }}</x-sg-label>
        <x-sg-text type="text" id="scopeInput" name="scope" :value="old('scope')" placeholder="" />
        <x-sg-alert-errors name="scope" />
    </div>
</div>

<!-- data_connection -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="data_connectionInput">{{ __('Data Connection') }}</x-sg-label>
        <x-sg-text type="text" id="data_connectionInput" name="data_connection" :value="old('data_connection')" placeholder="" />
        <x-sg-alert-errors name="data_connection" />
    </div>
</div>



                    <div class = "{{$decoration['class']['formfooter']}}" >
                        <x-sg-btn-submit />
                        <x-sg-btn-cancel />
                    </div>
                </div>
            </form>
        </x-slot>
        <x-slot name="cardFooterCenter">
            <x-sg-link-list href="{{route('storageconnections.index')}}" />
        </x-slot>
    </x-sg-card>

@push('css')
{{--pagespecific-css--}}
@endpush

@push('js')
{{--pagespecific-js--}}
@endpush

</x-sg-master>

src/resources/views/storageconnections/edit.blade.php
<x-sg-master>
    <x-sg-card>
        <x-slot name="heading">
            {{ __('StorageConnection') }}
        </x-slot>
        <x-slot name="body">
            <x-sg-alert-errors :errors="$errors" />
            <form action="{{ route('storageconnections.update', $storageconnection->uuid) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PATCH')
                <div class="row">
                    {{--relationalFields--}}
                    <!-- title -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="titleInput">{{ __('Title') }}</x-sg-label>
        <x-sg-text type="text" id="titleInput" name="title" :value="old('title', $storageconnection->title)" placeholder="" />
        <x-sg-alert-errors name="title" />
    </div>
</div>


<!-- storagetype_title -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="storagetype_titleInput">{{ __('Storagetype Title') }}</x-sg-label>
        <x-sg-selecttrio connection="keepmealone" tableName="storagetypes" name="storagetype" :selected="old('storagetype_id', $storageconnection->storagetype_id)"  />
        {{-- <sg-text type="text" id="storagetype_titleInput" name="storagetype_title" :value="old('storagetype_title', $storageconnection->storagetype_title)" placeholder="" /> --}}
        <x-sg-alert-errors name="storagetype_title" />
    </div>
</div>

<!-- target -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="targetInput">{{ __('Target') }}</x-sg-label>
        <x-sg-text type="text" id="targetInput" name="target" :value="old('target', $storageconnection->target)" placeholder="" />
        <x-sg-alert-errors name="target" />
    </div>
</div>

<!-- storage -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="storageInput">{{ __('Storage') }}</x-sg-label>
        <x-sg-text type="text" id="storageInput" name="storage" :value="old('storage', $storageconnection->storage)" placeholder="" />
        <x-sg-alert-errors name="storage" />
    </div>
</div>

<!-- client -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="clientInput">{{ __('Client') }}</x-sg-label>
        <x-sg-text type="text" id="clientInput" name="client" :value="old('client', $storageconnection->client)" placeholder="" />
        <x-sg-alert-errors name="client" />
    </div>
</div>

<!-- secret -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="secretInput">{{ __('Secret') }}</x-sg-label>
        <x-sg-text type="text" id="secretInput" name="secret" :value="old('secret', $storageconnection->secret)" placeholder="" />
        <x-sg-alert-errors name="secret" />
    </div>
</div>

<!-- encription -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="encriptionInput">{{ __('Encription') }}</x-sg-label>
        <x-sg-text type="text" id="encriptionInput" name="encription" :value="old('encription', $storageconnection->encription)" placeholder="" />
        <x-sg-alert-errors name="encription" />
    </div>
</div>

<!-- file_path -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="file_pathInput">{{ __('File Path') }}</x-sg-label>
        <x-sg-text type="text" id="file_pathInput" name="file_path" :value="old('file_path', $storageconnection->file_path)" placeholder="" />
        <x-sg-alert-errors name="file_path" />
    </div>
</div>

<!-- file_content -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="file_contentInput">{{ __('File Content') }}</x-sg-label>
        <x-sg-text type="text" id="file_contentInput" name="file_content" :value="old('file_content', $storageconnection->file_content)" placeholder="" />
        <x-sg-alert-errors name="file_content" />
    </div>
</div>

<!-- scope -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="scopeInput">{{ __('Scope') }}</x-sg-label>
        <x-sg-text type="text" id="scopeInput" name="scope" :value="old('scope', $storageconnection->scope)" placeholder="" />
        <x-sg-alert-errors name="scope" />
    </div>
</div>

<!-- data_connection -->
<div class="{{$decoration['class']['elementwrapper']}}" >
    <div class="{{$decoration['class']['elementcontainer'] }}" >
        <x-sg-label for="data_connectionInput">{{ __('Data Connection') }}</x-sg-label>
        <x-sg-text type="text" id="data_connectionInput" name="data_connection" :value="old('data_connection', $storageconnection->data_connection)" placeholder="" />
        <x-sg-alert-errors name="data_connection" />
    </div>
</div>



                    <div class = "{{$decoration['class']['formfooter']}}" >
                        <x-sg-btn-submit />
                        <x-sg-btn-cancel />
                    </div>
                </div>
            </form>
        </x-slot>
        <x-slot name="cardFooterCenter">
            <x-sg-link-list href="{{route('storageconnections.index')}}" />
        </x-slot>
    </x-sg-card>
@push('css')
{{--pagespecific-css--}}
@endpush

@push('js')
{{--pagespecific-js--}}
@endpush

</x-sg-master>

src/resources/views/storageconnections/index.blade.php
<x-sg-master>
    <x-sg-card>
        <x-slot name="heading">
            {{ __('StorageConnection') }}
        </x-slot>
        <x-slot name="body">
            <x-sg-alert-message :message="session('success')" type="success" />
            <x-sg-table type="basic"  id="storageconnectionDatatable">
                <x-sg-thead>
                    <tr>
                        <th>{{ __('SL') }}</th>
                            						<th>{{ __('Title') }}</th>
						<th>{{ __('Storagetype Title') }}</th>
						<th>{{ __('Target') }}</th>
						<th>{{ __('Storage') }}</th>
						<th>{{ __('Client') }}</th>
						<th>{{ __('Encription') }}</th>
						<th>{{ __('File Path') }}</th>

                        <th>{{ __('Actions' )}}</th>
                    </tr>
                </x-sg-thead>
                <x-sg-tbody>
                    @foreach ($storageconnections as $storageconnection)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $storageconnection->title }}</td>
						<td>{{ $storageconnection->storagetype_title }}</td>
						<td>{{ $storageconnection->target }}</td>
						<td>{{ $storageconnection->storage }}</td>
						<td>{{ $storageconnection->client }}</td>
						<td>{{ $storageconnection->encription }}</td>
						<td>{{ $storageconnection->file_path }}</td>

                        <td>
                            <x-sg-link-show href="{{route('storageconnections.show', $storageconnection->uuid)}}" />
                            {{-- <-sg-link-tree href="{{route('inputSpreadSheet')}}" /> --}}
                            <a class="btn btn-sm bg-green-800 border-2 border-green-800 btn-icon rounded-round legitRipple shadow mr-1" 
                            href="{{route('storageconnection', ['uuid' => $storageconnection->uuid])}}">
                            <i class="icon-file-spreadsheet2"></i></a>
                            <!-- <a class="btn btn-sm border-2 border-warning text-warning btn-icon rounded-round legitRipple shadow mr-1" href="route('inputSpreadSheet')}}"><i class="icon-file-spreadsheet2"></i></a> -->
                            <x-sg-link-edit href="{{route('storageconnections.edit', $storageconnection->uuid)}}" />
                            <x-sg-btn-delete action="{{route('storageconnections.destroy', $storageconnection->uuid)}}" method="post" />
                            <x-sg-link-history uuid="{{ $storageconnection->uuid }}"  api="/api/storageconnection-histories-list" />
                        </td>
                    </tr>
                    @endforeach
                </x-sg-tbody>
            </x-sg-table>
        </x-slot>
        <x-slot name="cardFooterCenter">

            <x-sg-link-create href="{{route('storageconnections.create')}}" />

        </x-slot>
    </x-sg-card>



@push('js')


<script>
   $(document).ready(function() {
        $('#storageconnectionDatatable').DataTable({
            buttons: [
                {
                    extend: 'colvis',
                    text: '<i class="icon-grid3"></i>',
                    className: 'btn bg-indigo-400 btn-icon dropdown-toggle'
                }
            ],
            stateSave: false,
            columnDefs: [
                {
                    targets: 0,
                    visible: true
                }
            ]
        });
    });
</script>
@endpush

</x-sg-master>

src/resources/views/storageconnections/show.blade.php
<x-sg-master>
    <x-sg-card>
        <x-slot name="heading">
            {{ __('StorageConnection') }}
        </x-slot>
        <x-slot name="body">
            <p><b>{{ __('Title') }} : </b> {{ $storageconnection->title }}</p>
			<p><b>{{ __('Storagetype Id') }} : </b> {{ $storageconnection->storagetype_id }}</p>
			<p><b>{{ __('Storagetype Uuid') }} : </b> {{ $storageconnection->storagetype_uuid }}</p>
			<p><b>{{ __('Storagetype Title') }} : </b> {{ $storageconnection->storagetype_title }}</p>
			<p><b>{{ __('Target') }} : </b> {{ $storageconnection->target }}</p>
			<p><b>{{ __('Storage') }} : </b> {{ $storageconnection->storage }}</p>
			<p><b>{{ __('Client') }} : </b> {{ $storageconnection->client }}</p>
			<p><b>{{ __('Secret') }} : </b> {{ $storageconnection->secret }}</p>
			<p><b>{{ __('Encription') }} : </b> {{ $storageconnection->encription }}</p>
			<p><b>{{ __('File Path') }} : </b> {{ $storageconnection->file_path }}</p>
			<p><b>{{ __('File Content') }} : </b> {{ $storageconnection->file_content }}</p>
			<p><b>{{ __('Scope') }} : </b> {{ $storageconnection->scope }}</p>
			<p><b>{{ __('Data Connection') }} : </b> {{ $storageconnection->data_connection }}</p>
			<p><b>{{ __('Qrcode') }} : </b> {{ $storageconnection->qrcode }}</p>
			
            {{--othersInfo--}}
        </x-slot>
        <x-slot name="cardFooterCenter">
            <x-sg-link-create href="{{route('storageconnections.index')}}" />
            <x-sg-link-list href="{{route('storageconnections.index')}}" />
            <x-sg-link-edit href="{{route('storageconnections.edit',$storageconnection->uuid)}}" />
            <x-sg-link-history uuid="{{$storageconnection->uuid}}" api="/api/storageconnections-histories-list" />
        </x-slot>
    </x-sg-card>

@push('css')
{{--pagespecific-css--}}
@endpush

@push('js')
{{--pagespecific-js--}}
@endpush
</x-sg-master>